export enum CategoryErrorKeyEnum {
  FAILED_TO_FETCH_CATEGORIES = 'Failed to fetch categories',
  FAILED_TO_FETCH_HOMEPAGE_CATEGORIES = 'Failed to fetch homepage categories',
  COMPANY_NOT_FOUND_FOR_DOMAIN_DOMAIN = 'Company not found for domain: ${domain}',
  FAILED_TO_CREATE_CATEGORY = 'FAILED TO CREATE CATEGORY',
  FAILED_TO_CREATE_CATEGORIES = 'FAILED TO CREATE CATEGORIES',
  FAILED_TO_UPDATE_CATEGORY = 'FAILED TO UPDATE CATEGORY',
  FAILED_TO_DELETE_CATEGORY = 'FAILED TO DELETE CATEGORY',
}
